/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour;

import javax.swing.JFrame;

/**
 * Connect Four
 * January 18, 2018
 * Jessica Zheng
 * A game that is a replica of the classic Connect Four, but this one has a few different modes to it.
 * Allows user to play against people or the computer. 
 */
public class MainPage extends javax.swing.JFrame {

    

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redBar = new javax.swing.JPanel();
        blueSquare2 = new javax.swing.JPanel();
        blueSquare1 = new javax.swing.JPanel();
        blueSquare3 = new javax.swing.JPanel();
        blueSquare4 = new javax.swing.JPanel();
        rulesBttn = new javax.swing.JButton();
        playBttn = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        connectFourImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        redBar.setBackground(new java.awt.Color(255, 51, 51));
        redBar.setForeground(new java.awt.Color(255, 51, 51));

        blueSquare2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout blueSquare2Layout = new javax.swing.GroupLayout(blueSquare2);
        blueSquare2.setLayout(blueSquare2Layout);
        blueSquare2Layout.setHorizontalGroup(
            blueSquare2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        blueSquare2Layout.setVerticalGroup(
            blueSquare2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        blueSquare1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout blueSquare1Layout = new javax.swing.GroupLayout(blueSquare1);
        blueSquare1.setLayout(blueSquare1Layout);
        blueSquare1Layout.setHorizontalGroup(
            blueSquare1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        blueSquare1Layout.setVerticalGroup(
            blueSquare1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        blueSquare3.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout blueSquare3Layout = new javax.swing.GroupLayout(blueSquare3);
        blueSquare3.setLayout(blueSquare3Layout);
        blueSquare3Layout.setHorizontalGroup(
            blueSquare3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        blueSquare3Layout.setVerticalGroup(
            blueSquare3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        blueSquare4.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout blueSquare4Layout = new javax.swing.GroupLayout(blueSquare4);
        blueSquare4.setLayout(blueSquare4Layout);
        blueSquare4Layout.setHorizontalGroup(
            blueSquare4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        blueSquare4Layout.setVerticalGroup(
            blueSquare4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        rulesBttn.setText("Rules");
        rulesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBttnActionPerformed(evt);
            }
        });

        playBttn.setText("Play");
        playBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redBarLayout = new javax.swing.GroupLayout(redBar);
        redBar.setLayout(redBarLayout);
        redBarLayout.setHorizontalGroup(
            redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redBarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(blueSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(blueSquare2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redBarLayout.createSequentialGroup()
                        .addComponent(playBttn)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redBarLayout.createSequentialGroup()
                        .addComponent(rulesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addComponent(blueSquare3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(blueSquare4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        redBarLayout.setVerticalGroup(
            redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redBarLayout.createSequentialGroup()
                .addGroup(redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(redBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blueSquare2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueSquare3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueSquare4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(redBarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(playBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rulesBttn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.setBackground(new java.awt.Color(255, 204, 204));

        title.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 150)); // NOI18N
        title.setText("Connect Four");

        connectFourImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectfour/Connect4Boardd.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(connectFourImage))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(title)
                .addGap(41, 41, 41)
                .addComponent(connectFourImage)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rulesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBttnActionPerformed
        //sets the Rules page visible and disposes current page
        JFrame rules = new Rules();
        rules.setVisible(true);
        this.dispose();
 
    }//GEN-LAST:event_rulesBttnActionPerformed

    private void playBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBttnActionPerformed
        //sets the modes menu page visible and disposes current page
        JFrame modesMenu = new ModesMenu();
        modesMenu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_playBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel blueSquare1;
    private javax.swing.JPanel blueSquare2;
    private javax.swing.JPanel blueSquare3;
    private javax.swing.JPanel blueSquare4;
    private javax.swing.JLabel connectFourImage;
    private javax.swing.JButton playBttn;
    private javax.swing.JPanel redBar;
    private javax.swing.JButton rulesBttn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
