/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour;

import javax.swing.JFrame;

/**
 * Connect Four 
 * January 18, 2018 
 * Jessica Zheng
 *
 */
public class ModesMenu extends javax.swing.JFrame {

    /**
     * Creates new form ModesMenu
     */
    public ModesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        twoPlayerBttn = new javax.swing.JButton();
        noGravityBttn = new javax.swing.JButton();
        easyBttn = new javax.swing.JButton();
        hardBttn = new javax.swing.JButton();
        threePlayerBttn = new javax.swing.JButton();
        upsideDownBttn = new javax.swing.JButton();
        modes = new javax.swing.JLabel();
        againstComp = new javax.swing.JLabel();
        twoPlayer = new javax.swing.JLabel();
        threePlayerMode = new javax.swing.JLabel();
        MenuBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        twoPlayerBttn.setText("Two Player");
        twoPlayerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayerBttnActionPerformed(evt);
            }
        });

        noGravityBttn.setText("No Gravity Mode");
        noGravityBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noGravityBttnActionPerformed(evt);
            }
        });

        easyBttn.setText("Easy");
        easyBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBttnActionPerformed(evt);
            }
        });

        hardBttn.setText("Hard");
        hardBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBttnActionPerformed(evt);
            }
        });

        threePlayerBttn.setText("Three Player");
        threePlayerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePlayerBttnActionPerformed(evt);
            }
        });

        upsideDownBttn.setText("Upside Down Two Player");
        upsideDownBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upsideDownBttnActionPerformed(evt);
            }
        });

        modes.setFont(new java.awt.Font("Arial", 1, 85)); // NOI18N
        modes.setText("Modes");

        againstComp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        againstComp.setText("Play Against the Computer:");

        twoPlayer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        twoPlayer.setText("Play Against Someone:");

        threePlayerMode.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        threePlayerMode.setText("Play Against 2 People:");

        MenuBttn.setText("Menu");
        MenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(modes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twoPlayer)
                            .addComponent(againstComp)
                            .addComponent(threePlayerMode))))
                .addGap(0, 228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upsideDownBttn)
                            .addComponent(twoPlayerBttn)
                            .addComponent(hardBttn)
                            .addComponent(easyBttn)
                            .addComponent(noGravityBttn)
                            .addComponent(threePlayerBttn))
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MenuBttn)
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(modes)
                .addGap(18, 18, 18)
                .addComponent(againstComp)
                .addGap(22, 22, 22)
                .addComponent(easyBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hardBttn)
                .addGap(22, 22, 22)
                .addComponent(twoPlayer)
                .addGap(10, 10, 10)
                .addComponent(twoPlayerBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upsideDownBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noGravityBttn)
                .addGap(27, 27, 27)
                .addComponent(threePlayerMode)
                .addGap(4, 4, 4)
                .addComponent(threePlayerBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(MenuBttn)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upsideDownBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upsideDownBttnActionPerformed
        //opens upsidedown mode and closes current page
        UpSideDown.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_upsideDownBttnActionPerformed

    private void easyBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBttnActionPerformed
        //opens ai easy mode and closes current page
        AI.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_easyBttnActionPerformed

    private void twoPlayerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayerBttnActionPerformed
        //opens two player mode and closes current page
        ConnectFourTwoPlayer.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_twoPlayerBttnActionPerformed

    private void noGravityBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noGravityBttnActionPerformed
        //opens no gravity mode and closes current page
        NoGravityMode.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_noGravityBttnActionPerformed

    private void threePlayerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePlayerBttnActionPerformed
        //opens three player mode and closes current page
        ConnectFourThreePlayer.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_threePlayerBttnActionPerformed

    private void hardBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBttnActionPerformed
        //opens the ai smart mode and closes current page
        AISmart.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_hardBttnActionPerformed

    private void MenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBttnActionPerformed
        //opens the menu page and closes current page
        JFrame mainMenu = new MainPage();
        mainMenu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_MenuBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuBttn;
    private javax.swing.JLabel againstComp;
    private javax.swing.JButton easyBttn;
    private javax.swing.JButton hardBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modes;
    private javax.swing.JButton noGravityBttn;
    private javax.swing.JButton threePlayerBttn;
    private javax.swing.JLabel threePlayerMode;
    private javax.swing.JLabel twoPlayer;
    private javax.swing.JButton twoPlayerBttn;
    private javax.swing.JButton upsideDownBttn;
    // End of variables declaration//GEN-END:variables
}
